package com.team9470;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.*;
import com.ctre.phoenix6.hardware.CANcoder;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.StaticFeedforwardSignValue;
import com.ctre.phoenix6.swerve.SwerveDrivetrain;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.ClosedLoopOutputType;
// import com.ctre.phoenix6.swerve.SwerveModuleConstants.DriveMotorArrangement;
// import com.ctre.phoenix6.swerve.SwerveModuleConstants.SteerMotorArrangement;
import com.ctre.phoenix6.swerve.SwerveModuleConstantsFactory;
import com.team9470.subsystems.swerve.Swerve;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.units.measure.*;

import static edu.wpi.first.units.Units.*;

// Generated by the Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public class TunerConstants {
        // Both sets of gains need to be tuned to your individual robot.

        // CAN bus that the devices are located on;
        // All swerve devices must share the same CAN bus
        public static final CANBus kCANBus = new CANBus("", "./logs/example.hoot");
        // Theoretical free speed (m/s) at 12 V applied output;
        // This needs to be tuned to your individual robot
        public static final LinearVelocity kSpeedAt12Volts = FeetPerSecond.of(14.4);
        // The steer motor uses any SwerveModule.SteerRequestType control request with
        // the
        // output type specified by SwerveModuleConstants.SteerMotorClosedLoopOutput
        public static final Slot0Configs steerGains = new Slot0Configs()
                        .withKP(100).withKI(0).withKD(1)
                        .withKS(.2).withKV(0).withKA(0)
                        .withStaticFeedforwardSign(StaticFeedforwardSignValue.UseClosedLoopSign);
        // When using closed-loop control, the drive motor uses the control
        // output type specified by SwerveModuleConstants.DriveMotorClosedLoopOutput
        public static final Slot0Configs driveGains = new Slot0Configs()
                        .withKP(10).withKI(0).withKD(0)
                        .withKS(1).withKV(0);
        // The closed-loop output type to use for the steer motors;
        // This affects the PID/FF gains for the steer motors
        private static final ClosedLoopOutputType kSteerClosedLoopOutput = ClosedLoopOutputType.Voltage;
        // The closed-loop output type to use for the drive motors;
        // This affects the PID/FF gains for the drive motors
        private static final ClosedLoopOutputType kDriveClosedLoopOutput = ClosedLoopOutputType.TorqueCurrentFOC;
        // The type of motor used for the drive motor
        private static final SwerveModuleConstants.DriveMotorArrangement kDriveMotorType = SwerveModuleConstants.DriveMotorArrangement.TalonFX_Integrated;
        // The type of motor used for the drive motor
        private static final SwerveModuleConstants.SteerMotorArrangement kSteerMotorType = SwerveModuleConstants.SteerMotorArrangement.TalonFX_Integrated;
        // The remote sensor feedback type to use for the steer motors;
        // When not Pro-licensed, FusedCANcoder/SyncCANcoder automatically fall back to
        // RemoteCANcoder
        private static final SwerveModuleConstants.SteerFeedbackType kSteerFeedbackType = SwerveModuleConstants.SteerFeedbackType.FusedCANcoder;
        // The stator current at which the wheels start to slip;
        // This needs to be tuned to your individual robot
        public static final Current kNominalSlipCurrent = Amps.of(60);
        public static final Current kTurboSlipCurrent = Amps.of(120);
        // Keep drive/steer limits explicit to avoid brownouts while preserving
        // traction.
        private static final Current kSteerStatorCurrentLimit = Amps.of(60);
        // Initial configs for the drive and steer motors and the azimuth encoder; these
        // cannot be null.
        // Some configs will be overwritten; check the `with*InitialConfigs()` API
        // documentation.
        private static final TalonFXConfiguration driveInitialConfigs = new TalonFXConfiguration();
        private static final TalonFXConfiguration steerInitialConfigs = new TalonFXConfiguration()
                        .withCurrentLimits(
                                        new CurrentLimitsConfigs()
                                                        // Swerve azimuth does not require much torque output, so we can
                                                        // set a relatively low
                                                        // stator current limit to help avoid brownouts without
                                                        // impacting performance.
                                                        .withStatorCurrentLimit(kSteerStatorCurrentLimit)
                                                        .withStatorCurrentLimitEnable(true));
        private static final CANcoderConfiguration encoderInitialConfigs = new CANcoderConfiguration();
        // Configs for the Pigeon 2; leave this null to skip applying Pigeon 2 configs
        private static final Pigeon2Configuration pigeonConfigs = new Pigeon2Configuration();

        static {
                /*
                 * The Pigeon 2 is mounted 90 degrees counter-clockwise from the robot-forward
                 * direction, so inform the device of the mount pose to ensure the reported
                 * yaw matches the robot coordinate frame.
                 */
                pigeonConfigs.MountPose.MountPoseYaw = 90.0;
        }
        // Every 1 rotation of the azimuth results in kCoupleRatio drive motor turns.
        // CTRE defines this as the inverse of the 1st drive stage. For SDS MK5n R1
        // with a 12T driving gear into a 54T driven gear, that is 54/12 = 4.5.
        // Verify this on hardware after assembly.
        private static final double kCoupleRatio = 4.5;

        // SDS MK5n R1 drive ratio and MK5n steering ratio.
        private static final double kDriveGearRatio = 7.03;
        private static final double kSteerGearRatio = 26.09;
        private static final Distance kWheelRadius = Inches.of(1.95);

        private static final boolean kInvertLeftSide = false;
        private static final boolean kInvertRightSide = true;

        private static final int kPigeonId = 0;
        public static final SwerveDrivetrainConstants DrivetrainConstants = new SwerveDrivetrainConstants()
                        .withCANBusName(kCANBus.getName())
                        .withPigeon2Id(kPigeonId)
                        .withPigeon2Configs(pigeonConfigs);
        // These are only used for simulation
        private static final MomentOfInertia kSteerInertia = KilogramSquareMeters.of(0.01);
        private static final MomentOfInertia kDriveInertia = KilogramSquareMeters.of(0.01);
        // Simulated voltage necessary to overcome friction
        private static final Voltage kSteerFrictionVoltage = Volts.of(0.2);
        private static final Voltage kDriveFrictionVoltage = Volts.of(0.2);
        private static final SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> ConstantCreator = new SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>()
                        .withDriveMotorGearRatio(kDriveGearRatio)
                        .withSteerMotorGearRatio(kSteerGearRatio)
                        .withCouplingGearRatio(kCoupleRatio)
                        .withWheelRadius(kWheelRadius)
                        .withSteerMotorGains(steerGains)
                        .withDriveMotorGains(driveGains)
                        .withSteerMotorClosedLoopOutput(kSteerClosedLoopOutput)
                        .withDriveMotorClosedLoopOutput(kDriveClosedLoopOutput)
                        .withSlipCurrent(kNominalSlipCurrent)
                        .withSpeedAt12Volts(kSpeedAt12Volts)
                        .withDriveMotorType(kDriveMotorType)
                        .withSteerMotorType(kSteerMotorType)
                        .withFeedbackSource(kSteerFeedbackType)
                        .withDriveMotorInitialConfigs(driveInitialConfigs)
                        .withSteerMotorInitialConfigs(steerInitialConfigs)
                        .withEncoderInitialConfigs(encoderInitialConfigs)
                        .withSteerInertia(kSteerInertia)
                        .withDriveInertia(kDriveInertia)
                        .withSteerFrictionVoltage(kSteerFrictionVoltage)
                        .withDriveFrictionVoltage(kDriveFrictionVoltage);

        // pathfinding constraints
        public static final double maxVelocity = kSpeedAt12Volts.in(MetersPerSecond) * .6;
        public static final double maxAcceleration = 9.812;
        public static final double maxAngularVelocity = 572.96; // degrees
        public static final double maxAngularAcceleration = 2480.33; // degrees

        // Front Left
        private static final int kFrontLeftDriveMotorId = 1;
        private static final int kFrontLeftSteerMotorId = 2;
        private static final int kFrontLeftEncoderId = 3;
        private static final Angle kFrontLeftEncoderOffset = Rotations.of(-0.436767578125);
        private static final boolean kFrontLeftSteerMotorInverted = false;
        private static final boolean kFrontLeftEncoderInverted = false;

        private static final Distance kFrontLeftXPos = Inches.of(10.875);
        private static final Distance kFrontLeftYPos = Inches.of(10.875);
        public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontLeft = ConstantCreator
                        .createModuleConstants(
                                        kFrontLeftSteerMotorId, kFrontLeftDriveMotorId, kFrontLeftEncoderId,
                                        kFrontLeftEncoderOffset,
                                        kFrontLeftXPos, kFrontLeftYPos, kInvertLeftSide, kFrontLeftSteerMotorInverted,
                                        kFrontLeftEncoderInverted);
        // Front Right
        private static final int kFrontRightDriveMotorId = 4;
        private static final int kFrontRightSteerMotorId = 5;
        private static final int kFrontRightEncoderId = 6;
        private static final Angle kFrontRightEncoderOffset = Rotations.of(0.00146484375);
        private static final boolean kFrontRightSteerMotorInverted = false;
        private static final boolean kFrontRightEncoderInverted = false;
        private static final Distance kFrontRightXPos = Inches.of(10.875);
        private static final Distance kFrontRightYPos = Inches.of(-10.875);
        public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontRight = ConstantCreator
                        .createModuleConstants(
                                        kFrontRightSteerMotorId, kFrontRightDriveMotorId, kFrontRightEncoderId,
                                        kFrontRightEncoderOffset,
                                        kFrontRightXPos, kFrontRightYPos, kInvertRightSide,
                                        kFrontRightSteerMotorInverted, kFrontRightEncoderInverted);
        // Back Right
        private static final int kBackRightDriveMotorId = 10;
        private static final int kBackRightSteerMotorId = 11;
        private static final int kBackRightEncoderId = 12;
        private static final Angle kBackRightEncoderOffset = Rotations.of(0.175048828125);
        private static final boolean kBackRightSteerMotorInverted = false;
        private static final boolean kBackRightEncoderInverted = false;
        private static final Distance kBackRightXPos = Inches.of(-10.875);
        private static final Distance kBackRightYPos = Inches.of(-10.875);
        public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackRight = ConstantCreator
                        .createModuleConstants(
                                        kBackRightSteerMotorId, kBackRightDriveMotorId, kBackRightEncoderId,
                                        kBackRightEncoderOffset,
                                        kBackRightXPos, kBackRightYPos, kInvertRightSide, kBackRightSteerMotorInverted,
                                        kBackRightEncoderInverted);
        // Back Left
        private static final int kBackLeftDriveMotorId = 7;
        private static final int kBackLeftSteerMotorId = 8;
        private static final int kBackLeftEncoderId = 9;
        private static final Angle kBackLeftEncoderOffset = Rotations.of(0.489013671875);
        private static final boolean kBackLeftSteerMotorInverted = false;
        private static final boolean kBackLeftEncoderInverted = false;
        private static final Distance kBackLeftXPos = Inches.of(-10.875);
        private static final Distance kBackLeftYPos = Inches.of(10.875);
        public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackLeft = ConstantCreator
                        .createModuleConstants(
                                        kBackLeftSteerMotorId, kBackLeftDriveMotorId, kBackLeftEncoderId,
                                        kBackLeftEncoderOffset,
                                        kBackLeftXPos, kBackLeftYPos, kInvertLeftSide, kBackLeftSteerMotorInverted,
                                        kBackLeftEncoderInverted);

        // STDDEVS
        public static final Matrix<N3, N1> odometryStandardDeviation = new Matrix<>(
                        VecBuilder.fill(0.003, 0.003, 0.002));
        public static final Matrix<N3, N1> visionStandardDeviation = new Matrix<>(VecBuilder.fill(0.02, 0.02, 0.02));

        /**
         * Creates a CommandSwerveDrivetrain instance.
         * This should only be called once in your robot program,.
         */
        public static Swerve createDrivetrain() {
                return new Swerve(DrivetrainConstants,
                                100, odometryStandardDeviation, visionStandardDeviation,
                                FrontLeft, FrontRight, BackLeft, BackRight);

        }

        /**
         * Swerve Drive class utilizing CTR Electronics' Phoenix 6 API with the selected
         * device types.
         */
        public static class TunerSwerveDrivetrain extends SwerveDrivetrain<TalonFX, TalonFX, CANcoder> {
                /**
                 * Constructs a CTRE SwerveDrivetrain using the specified constants.
                 * <p>
                 * This constructs the underlying hardware devices, so users should not
                 * construct
                 * the devices themselves. If they need the devices, they can access them
                 * through
                 * getters in the classes.
                 *
                 * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
                 * @param modules             Constants for each specific module
                 */
                public TunerSwerveDrivetrain(
                                SwerveDrivetrainConstants drivetrainConstants,
                                SwerveModuleConstants<?, ?, ?>... modules) {
                        super(
                                        TalonFX::new, TalonFX::new, CANcoder::new,
                                        drivetrainConstants, modules);
                }

                /**
                 * Constructs a CTRE SwerveDrivetrain using the specified constants.
                 * <p>
                 * This constructs the underlying hardware devices, so users should not
                 * construct
                 * the devices themselves. If they need the devices, they can access them
                 * through
                 * getters in the classes.
                 *
                 * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
                 * @param odometryUpdateFrequency The frequency to run the odometry loop. If
                 *                                unspecified or set to 0 Hz, this is 250 Hz on
                 *                                CAN FD, and 100 Hz on CAN 2.0.
                 * @param modules                 Constants for each specific module
                 */
                public TunerSwerveDrivetrain(
                                SwerveDrivetrainConstants drivetrainConstants,
                                double odometryUpdateFrequency,
                                SwerveModuleConstants<?, ?, ?>... modules) {
                        super(
                                        TalonFX::new, TalonFX::new, CANcoder::new,
                                        drivetrainConstants, odometryUpdateFrequency, modules);
                }

                /**
                 * Constructs a CTRE SwerveDrivetrain using the specified constants.
                 * <p>
                 * This constructs the underlying hardware devices, so users should not
                 * construct
                 * the devices themselves. If they need the devices, they can access them
                 * through
                 * getters in the classes.
                 *
                 * @param drivetrainConstants       Drivetrain-wide constants for the swerve
                 *                                  drive
                 * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
                 *                                  unspecified or set to 0 Hz, this is 250 Hz
                 *                                  on
                 *                                  CAN FD, and 100 Hz on CAN 2.0.
                 * @param odometryStandardDeviation The standard deviation for odometry
                 *                                  calculation
                 *                                  in the form [x, y, theta]ᵀ, with units in
                 *                                  meters
                 *                                  and radians
                 * @param visionStandardDeviation   The standard deviation for vision
                 *                                  calculation
                 *                                  in the form [x, y, theta]ᵀ, with units in
                 *                                  meters
                 *                                  and radians
                 * @param modules                   Constants for each specific module
                 */
                public TunerSwerveDrivetrain(
                                SwerveDrivetrainConstants drivetrainConstants,
                                double odometryUpdateFrequency,
                                Matrix<N3, N1> odometryStandardDeviation,
                                Matrix<N3, N1> visionStandardDeviation,
                                SwerveModuleConstants<?, ?, ?>... modules) {
                        super(
                                        TalonFX::new, TalonFX::new, CANcoder::new,
                                        drivetrainConstants, odometryUpdateFrequency,
                                        odometryStandardDeviation, visionStandardDeviation, modules);
                }
        }
}
